### ISSUE TITLE
Are config file working correct?

### ISSUE THREAD

**Issue by VladislavSournine** [domohuhn/mutation-test#26] opened 2024-08-20 05:58 UTC
Run mutation-test -s
Got config file.
Change in <files> to my file
run again 
`dart run mutation_test ./config.xml`
Got error:
`Error while processing:
  Error: There must be only one <threshold> element in the inputs!`

But config contains defaults:

`<threshold failure="80">
        
        <rating over="95" name="A"/>
        <rating over="80" name="B"/>
        <rating over="60" name="C"/>
        <rating over="40" name="D"/>
        <rating over="20" name="E"/>
        <rating over="0" name="F"/>
    </threshold>`
    
  Where is my mistake?

**Comment by domohuhn** [comment] 2024-09-01 17:07
The problem is that the builtin-ruleset already has the thresholds defined. The rules you generate via the -s option are always injected into your program call. I will have to include a check for user defined values before including the builtin thresholds.

As workaround for now you can either remove  the thresold section from you config your add the flag --no-builtin

**Comment by domohuhn** [comment] 2024-09-01 18:00
The problem should be fixed in v1.7.0

**Closed as completed by domohuhn** 2024-09-01 18:00 UTC
